% Attitude 서브시스템: ADRC → Geometric Controller 교체
att = 'flightController/Flight Controller/Attitude';

load_system('controller/flightController');

%% 1. 기존 내부 블록 전부 삭제 (Inport/Outport 제외)
all_blocks = find_system(att, 'SearchDepth', 1, 'Type', 'Block');
for i = 1:length(all_blocks)
    if strcmp(all_blocks{i}, att), continue; end
    bt = get_param(all_blocks{i}, 'BlockType');
    if ~strcmp(bt, 'Inport') && ~strcmp(bt, 'Outport')
        delete_block(all_blocks{i});
    end
end
disp('기존 블록 삭제 완료');

%% 2. 기존 Inport에 Terminator 연결 (refAttitude, states_estim 안 쓰지만 포트 유지)
add_block('built-in/Terminator', [att '/Term_ref'],    'Position', [120, 60, 140, 80]);
add_block('built-in/Terminator', [att '/Term_states'], 'Position', [120, 110, 140, 130]);
add_line(att, 'refAttitude/1',  'Term_ref/1');
add_line(att, 'states_estim/1', 'Term_states/1');

%% 3. 새 Inport 추가: R_meas [3x3], Omega_meas [3x1]
add_block('built-in/Inport', [att '/R_meas'], ...
    'Position',       [30, 170, 60, 185], ...
    'Port',           '3', ...
    'PortDimensions', '[3 3]');

add_block('built-in/Inport', [att '/Omega_meas'], ...
    'Position',       [30, 220, 60, 235], ...
    'Port',           '4', ...
    'PortDimensions', '[3 1]');
disp('새 Inport 추가 완료');

%% 4. MATLAB Function 블록 추가
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [att '/GeometricController'], ...
    'Position', [200, 170, 380, 240]);
disp('MATLAB Function 블록 추가 완료');

%% 5. 함수 내용 설정
rt = sfroot;
chart = rt.find('-isa', 'Stateflow.EMChart', ...
    'Path', [att '/GeometricController']);

chart.Script = sprintf([...
'function [tau_pitch, tau_roll] = GeometricController(R, W)\n'...
'kR  = 0.0005;\n'...
'kW  = 0.0001;\n'...
'J   = diag([5.82857e-5, 7.16914e-5, 1e-4]);\n'...
'R_des = eye(3);       %% hover: 나중에 플립 궤적으로 교체\n'...
'W_des = zeros(3,1);\n'...
'\n'...
'eR = vee(0.5*(R_des''*R - R''*R_des));\n'...
'eW = W - R''*R_des*W_des;\n'...
'tau = -kR*eR - kW*eW + cross(W, J*W);\n'...
'tau_pitch = single(tau(2));\n'...
'tau_roll  = single(tau(1));\n'...
'end\n'...
'\n'...
'function v = vee(M)\n'...
'v = [M(3,2); M(1,3); M(2,1)];\n'...
'end\n'...
]);
disp('함수 내용 설정 완료');

%% 6. 배선 연결
add_line(att, 'R_meas/1',           'GeometricController/1');
add_line(att, 'Omega_meas/1',        'GeometricController/2');
add_line(att, 'GeometricController/1', 'tau_pitch/1');
add_line(att, 'GeometricController/2', 'tau_roll/1');
disp('배선 연결 완료');

%% 7. 저장
save_system('controller/flightController');
disp('저장 완료');
